package com.clonemaster.ui

import com.clonemaster.cloning.engine.OptionalFeatures
import com.clonemaster.cloning.models.CloneConfig
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Option-state regression tests for the "0/83 must mean ZERO ACTIVE options" rule.
 *
 * A displayed value (Android ID, IMEI, "pixel8_pro", WebView UA, ...) is NEVER
 * an enabled feature by itself: activation is gated by the matching spoof flag.
 * The enabled count must be derived from the saved CloneConfig (OptionState),
 * not from displayed values, and preset-activated features must be visible.
 */
class OptionStateTest {

    private val registry = OptionRegistry.getAllOptions()

    @Test
    fun `caseA fresh config - zero enabled options and no identity applied`() {
        val config = CloneConfig()
        // values exist by default (random/generated)...
        assertTrue("androidId value is generated by default", config.identity.androidId.isNotEmpty())
        assertTrue("imei value is generated by default", config.identity.imei.isNotEmpty())
        assertEquals("pixel8_pro", config.environment.physicalDeviceProfileId)
        // ...but they must not make any option active
        assertEquals("0 enabled options", 0, OptionState.enabledCount(config, registry))
        assertFalse("no optional features may be applied", OptionalFeatures.anyEnabled(config))
    }

    @Test
    fun `caseB enable exactly one option - counter becomes 1`() {
        val config = CloneConfig()
        config.display.keepScreenAwake = true
        assertEquals(1, OptionState.enabledCount(config, registry))
        val enabled = OptionState.enabledOptions(config, registry)
        assertEquals(1, enabled.size)
        assertEquals("display.keepScreenAwake", enabled[0].fieldPath)
        assertEquals("display_keepAwake", enabled[0].optionId)
    }

    @Test
    fun `caseC several options - counter matches and dedupes shared fields`() {
        val config = CloneConfig()
        config.display.keepScreenAwake = true
        config.environment.hideRoot = true      // shared by "Root Hide" AND "Hide Root" entries
        config.dataBundle.enabled = true
        assertEquals(3, OptionState.enabledCount(config, registry))
        val paths = OptionState.enabledOptions(config, registry).map { it.fieldPath }
        assertEquals(
            "shared field environment.hideRoot must count once",
            1, paths.count { it == "environment.hideRoot" }
        )
    }

    @Test
    fun `caseD configured value without enable flag - never applied, count stays 0`() {
        val config = CloneConfig()
        config.identity.androidId = "0123456789abcdef"
        config.identity.imei = "351234567890123"
        config.environment.physicalDeviceProfileId = "s24_ultra"
        // values present, feature flags OFF
        assertEquals(0, OptionState.enabledCount(config, registry))
        assertFalse(OptionalFeatures.anyEnabled(config))

        // enabling the flag activates exactly that option (value retained)
        config.identity.spoofAndroidId = true
        assertEquals(1, OptionState.enabledCount(config, registry))
        assertTrue(OptionalFeatures.anyEnabled(config))

        // disabling again: value may remain but feature is not applied
        config.identity.spoofAndroidId = false
        assertEquals(0, OptionState.enabledCount(config, registry))
        assertFalse(OptionalFeatures.anyEnabled(config))
        assertEquals("value survives disable (stored, not applied)", "0123456789abcdef", config.identity.androidId)
    }

    @Test
    fun `preset-activated flags are visible - no hidden enabled options`() {
        val config = CloneConfig()
        val presetApplied = PresetManager.applyPreset(config, PresetType.PRIVACY)
        val count = OptionState.enabledCount(presetApplied, registry)
        assertTrue("PRIVACY preset must produce visible enabled options, got $count", count > 0)
        val names = OptionState.enabledOptions(presetApplied, registry).map { it.optionName }
        assertTrue(
            "identity spoofing enabled by the preset must be counted/visible: $names",
            names.any { it.contains("Android ID") }
        )
    }

    @Test
    fun `device profile default is value-only - spoof option inactive until flag set`() {
        val config = CloneConfig()
        assertEquals("pixel8_pro", config.environment.physicalDeviceProfileId)
        val profileOption = registry.first { it.configFieldPath == "environment.physicalDeviceProfileId" }
        assertFalse(
            "profile dropdown value alone must NOT count as enabled",
            OptionState.isEnabled(config, profileOption.configFieldPath)
        )
        config.environment.spoofPhysicalDeviceProfile = true
        assertTrue(
            "profile spoofing counts only when its enable flag is set",
            OptionState.isEnabled(config, profileOption.configFieldPath)
        )
    }
}
