package com.clonemaster.core.cloner.dex

import org.jf.dexlib2.Opcodes
import org.jf.dexlib2.ReferenceType
import org.jf.dexlib2.builder.instruction.BuilderInstruction21c
import org.jf.dexlib2.builder.instruction.BuilderInstruction31c
import org.jf.dexlib2.dexbacked.DexBackedDexFile
import org.jf.dexlib2.iface.DexFile
import org.jf.dexlib2.iface.instruction.Instruction
import org.jf.dexlib2.iface.instruction.ReferenceInstruction
import org.jf.dexlib2.iface.instruction.formats.Instruction21c
import org.jf.dexlib2.iface.instruction.formats.Instruction31c
import org.jf.dexlib2.iface.reference.StringReference
import org.jf.dexlib2.iface.value.EncodedValue
import org.jf.dexlib2.iface.value.StringEncodedValue
import org.jf.dexlib2.immutable.reference.ImmutableStringReference
import org.jf.dexlib2.immutable.value.ImmutableStringEncodedValue
import org.jf.dexlib2.rewriter.DexRewriter
import org.jf.dexlib2.rewriter.EncodedValueRewriter
import org.jf.dexlib2.rewriter.InstructionRewriter
import org.jf.dexlib2.rewriter.Rewriter
import org.jf.dexlib2.rewriter.RewriterModule
import org.jf.dexlib2.rewriter.Rewriters
import org.jf.dexlib2.writer.io.MemoryDataStore
import org.jf.dexlib2.writer.pool.DexPool

/**
 * Full DEX transformation/rebuild engine (based on org.smali:dexlib2, Apache-2.0).
 *
 * This REPLACES the previous in-place footprint-preserving string patcher, which
 * could only rewrite strings whose replacement was SHORTER or EQUAL ("NOT FITTED"
 * for any longer package name). dexlib2 parses the DEX into an object model and
 * re-emits a NEW dex file on write (DexPool), so:
 *
 *   - the string pool is fully REBUILT  -> replacements may be any length,
 *   - all offsets/IDs/class_defs/code are regenerated by the writer,
 *   - type descriptors (class Lpkg/Name;) are renamed with every
 *     field/method/type reference updated coherently,
 *   - const-string / const-string/jumbo operands and encoded string values are
 *     rewritten,
 *   - multidex is handled by rewriting each classesN.dex independently,
 *   - the writer recomputes the DEX header, data map, signature and checksum.
 *
 * The "must fit in old string space" limitation does NOT exist here.
 */
class DexPackageRewriter(
    private val originalPackage: String,
    private val newPackage: String,
    authorities: Map<String, String> = emptyMap()
) {

    private val replacements: Map<String, String> = buildMap {
        authorities.forEach { (k, v) -> put(k, v) }
        put(originalPackage, newPackage)
    }

    private val origSlash = originalPackage.replace('.', '/')
    private val newSlash = newPackage.replace('.', '/')
    private val origPrefix = "$origSlash/"
    private val newPrefix = "$newSlash/"

    /** Result of one dex file rewrite. */
    class DexResult(
        val dex: ByteArray,
        val rewrittenStrings: Int,
        val rewrittenTypes: Int,
        val classes: List<String>
    )

    /** Rewrites one dex file (any classesN.dex) and returns the new bytes. */
    fun rewrite(dexBytes: ByteArray): DexResult {
        val opcodes = Opcodes.forApi(28)
        val dexFile = DexBackedDexFile(opcodes, dexBytes)

        val counters = IntArray(2) // 0 = strings, 1 = types
        val module = object : RewriterModule() {
            override fun getTypeRewriter(rewriters: Rewriters): Rewriter<String> =
                Rewriter { t -> rewriteType(t)?.also { counters[1]++ } ?: t }

            override fun getInstructionRewriter(rewriters: Rewriters): Rewriter<Instruction> =
                object : InstructionRewriter(rewriters) {
                    override fun rewrite(instruction: Instruction): Instruction {
                        if (instruction !is ReferenceInstruction ||
                            instruction.referenceType != ReferenceType.STRING
                        ) return super.rewrite(instruction)
                        val strRef = instruction.reference
                        if (strRef !is StringReference) return super.rewrite(instruction)

                        val newStr = rewriteString(strRef.string)
                            ?: return super.rewrite(instruction)
                        return when (instruction) {
                            is Instruction21c ->
                                BuilderInstruction21c(instruction.opcode, instruction.registerA, ImmutableStringReference(newStr))
                            is Instruction31c ->
                                BuilderInstruction31c(instruction.opcode, instruction.registerA, ImmutableStringReference(newStr))
                            else -> super.rewrite(instruction)
                        }.also { counters[0]++ }
                    }
                }

            override fun getEncodedValueRewriter(rewriters: Rewriters): Rewriter<EncodedValue> =
                object : EncodedValueRewriter(rewriters) {
                    override fun rewrite(value: EncodedValue): EncodedValue {
                        if (value is StringEncodedValue) {
                            val newStr = rewriteString(value.value)
                            if (newStr != null) {
                                counters[0]++
                                return ImmutableStringEncodedValue(newStr)
                            }
                        }
                        return super.rewrite(value)
                    }
                }
        }

        val rewritten: DexFile = DexRewriter(module).getDexFileRewriter().rewrite(dexFile)

        // Re-serialize: DexPool interns every class and writes a fresh dex
        // (string pool rebuilt; map/header/checksum regenerated by the writer).
        val pool = DexPool(opcodes)
        rewritten.classes.forEach { pool.internClass(it) }
        val store = MemoryDataStore()
        pool.writeTo(store)

        return DexResult(store.data, counters[0], counters[1], rewritten.classes.map { it.type })
    }

    // ---------------------------------------------------------------- rules

    /** Rewrites a plain string literal when it references the original package. */
    fun rewriteString(s: String): String? {
        replacements[s]?.let { return it }
        // Prefix rule: "com.example.app.foo", "com.example.app/path", ":remote"
        // process names etc. -> new package + remainder. Only when the string
        // starts with the exact original package followed by a delimiter.
        if (s.length > originalPackage.length && s.startsWith(originalPackage)) {
            val rest = s.substring(originalPackage.length)
            if (rest.startsWith(".") || rest.startsWith("/") || rest.startsWith(":") || rest.startsWith("_")) {
                return newPackage + rest
            }
        }
        // Embedded-descriptor rule (REGRESSION FIX – device crash):
        // generic Signature annotations and reflection lookups embed ONE OR MORE
        // descriptors inside a larger string, e.g.
        //   "Ljava/util/List<Lcom/pkg/models/Foo;>;"        (Kotlin/Java generic of a field)
        //   "(Lcom/pkg/A;Ljava/lang/String;)V"              (method generic)
        //   "Lcom/pkg/Foo;"                                 (Class.forName descriptor)
        // The exact/prefix rules above cannot match these, so reflection
        // (Gson/Jackson/Moshi/Room/Retrofit…) resolved the OLD name at runtime:
        // ClassNotFoundException / TypeNotPresentException inside clones.
        // Rule: every "L<origSlash>/" occurrence is rewritten to the clone slug.
        // Only the descriptor form ("L"+slug+"/") matches, plain text is untouched.
        if (s.contains("L$origPrefix")) {
            return s.replace("L$origPrefix", "L$newPrefix")
        }
        return null
    }

    /**
     * Rewrites a type descriptor: Lcom/example/Foo; or array form
     * [Lcom/example/Foo;. Only the ORIGINAL package path is renamed — third-party
     * types are never touched.
     */
    fun rewriteType(t: String): String? {
        if (t == "L$origSlash;") return "L$newSlash;"
        if (t.startsWith("L") && t.endsWith(";")) {
            val inner = t.substring(1, t.length - 1)
            if (inner == origSlash) return "L$newSlash;"
            if (inner.startsWith(origPrefix)) return "L$newPrefix" + inner.substring(origPrefix.length) + ";"
            return null
        }
        if (t.startsWith("[")) {
            val stripped = t.trimStart('[')
            val newType = rewriteType(stripped) ?: return null
            return t.replaceRange(t.length - stripped.length, t.length, newType)
        }
        return null
    }

    // ------------------------------------------------------------ utilities

    companion object {
        /** Parses a dex and returns the class type descriptors (for validation). */
        fun listClasses(dexBytes: ByteArray): List<String> =
            try {
                DexBackedDexFile(Opcodes.forApi(28), dexBytes).classes.map { it.type }
            } catch (e: Exception) {
                emptyList()
            }

        fun toDescriptor(className: String): String {
            val c = className.trimStart('.')
            return "L" + c.replace('.', '/') + ";"
        }

        fun fromDescriptor(d: String): String =
            d.removePrefix("L").removeSuffix(";").replace('/', '.')
    }
}
